lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
# theme: minimnal
title: Mike Gifford
# logo: /assets/img/logo.png
description: Personal landing page
show_downloads: false
theme: jekyll-theme-minimal
